import { MediaItem } from './types';

export const HERO_IMAGE = "https://picsum.photos/id/180/1920/1080"; 

export const SAMPLE_MEDIA: MediaItem[] = [
  {
    id: '1',
    type: 'image',
    url: 'https://picsum.photos/id/129/800/1200',
    thumbnail: 'https://picsum.photos/id/129/400/600',
    title: 'Sunday Morning',
    date: '2023-10-15',
    description: 'Sunlight streaming through an open window, dust motes dancing in the air.',
    aspectRatio: 'aspect-[2/3]',
  },
  {
    id: '2',
    type: 'image',
    url: 'https://picsum.photos/id/338/1200/800',
    thumbnail: 'https://picsum.photos/id/338/600/400',
    title: 'The Old Station',
    date: '2023-09-22',
    description: 'Friends waiting on a train platform, laughing, with golden hour light.',
    aspectRatio: 'aspect-[3/2]',
  },
  {
    id: '3',
    type: 'image',
    url: 'https://picsum.photos/id/435/800/800',
    thumbnail: 'https://picsum.photos/id/435/400/400',
    title: 'Coffee & Rain',
    date: '2023-11-02',
    description: 'Two cups of coffee on a wooden table while it rains outside.',
    aspectRatio: 'aspect-square',
  },
  {
    id: '4',
    type: 'image',
    url: 'https://picsum.photos/id/65/800/1200',
    thumbnail: 'https://picsum.photos/id/65/400/600',
    title: 'Roadtrip',
    date: '2023-08-14',
    description: 'A girl looking out the window of a car, hair blowing in the wind.',
    aspectRatio: 'aspect-[2/3]',
  },
  {
    id: '5',
    type: 'image',
    url: 'https://picsum.photos/id/250/800/600',
    thumbnail: 'https://picsum.photos/id/250/400/300',
    title: 'Disposable Camera',
    date: '2023-12-25',
    description: 'A blurry but happy photo of a group dinner with candles.',
    aspectRatio: 'aspect-[4/3]',
  },
  {
    id: '6',
    type: 'image',
    url: 'https://picsum.photos/id/342/800/800',
    thumbnail: 'https://picsum.photos/id/342/400/400',
    title: 'City Walk',
    date: '2024-01-10',
    description: 'Walking through the city at dusk, streetlights just turning on.',
    aspectRatio: 'aspect-square',
  },
  {
    id: '7',
    type: 'image',
    url: 'https://picsum.photos/id/453/1200/800',
    thumbnail: 'https://picsum.photos/id/453/600/400',
    title: 'Beach Bonfire',
    date: '2023-07-30',
    description: 'Sparks flying from a bonfire on the beach at night.',
    aspectRatio: 'aspect-[3/2]',
  },
  {
    id: '8',
    type: 'image',
    url: 'https://picsum.photos/id/551/800/1200',
    thumbnail: 'https://picsum.photos/id/551/400/600',
    title: 'Library',
    date: '2023-10-05',
    description: 'Quiet time reading books in an old library with wooden shelves.',
    aspectRatio: 'aspect-[2/3]',
  },
];
